[package]
name = "gafctl-bluetooth"
version = "0.1.1"
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Bluetooth transport for GAF Master Flow attic fans"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
backon = { workspace = true, features = ["std"] }
btleplug.workspace = true
bytes.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "sync", "time"] }
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
gafctl-protocol = { version = "0.1.1", path = "../gafctl-protocol" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[target.'cfg(target_os = "linux")'.dependencies]
bluez-async = "0.8.2"

[target.'cfg(target_os = "linux")'.dev-dependencies]
dbus = "0.9.12"
serde_json.workspace = true
