[package]
name = "gafctl-protocol"
version = "0.1.1"
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Protocol types and codecs for GAF Master Flow attic fans"

[lints]
workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
