[package]
name = "gafctl-client"
version = "0.1.0"
edition = "2024"
description = "Typed asynchronous client for a running Gafctl service"

[lints]
workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
gafctl-api = { path = "../gafctl-api" }

[dev-dependencies]
tokio-util.workspace = true
axum.workspace = true
bytes.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time", "sync"] }
