[package]
name = "gafctl-client"
version = "0.1.1"
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Typed asynchronous client for a running Gafctl service"

[lints]
workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
gafctl-api = { version = "0.1.1", path = "../gafctl-api" }

[dev-dependencies]
tokio-util.workspace = true
axum.workspace = true
bytes.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time", "sync"] }
